// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Curry     = require("bs-platform/lib/js/curry.js");
var Servo_dom = require("./servo_dom.js");

var $$document = window.document;

var elem = $$document.getElementById("sample");

var now = window.performance.now();

window.alert("first");

function handler_001(x) {
  window.alert(x);
  return /* () */0;
}

var handler = /* `Callback */[
  -659008027,
  handler_001
];

Curry._5(Servo_dom.Window[/* setTimeout */7], window, handler, /* Some */[1000], /* array */["called"], /* () */0);

window.alert("end");

var elem$1 = elem === null ? /* None */0 : [elem];

exports.$$document = $$document;
exports.elem       = elem$1;
exports.now        = now;
/* document Not a pure module */
