// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry        = require("bs-platform/lib/js/curry.js");
var Js_math      = require("bs-platform/lib/js/js_math.js");
var Particle     = require("./particle.js");
var Draw_objects = require("./draw_objects.js");

function is_delete_elem(elem) {
  return +(elem[/* speed */3] <= 1);
}

function action_when_delete(elem) {
  var count = Js_math.random_int(25, 50);
  return Curry._4(Particle.create, count, elem[/* hue */6], elem[/* x */0], elem[/* y */1]);
}

function create_elem(base_hue, x, y) {
  return Draw_objects.create_elem(3, x, y, Draw_objects.random(15, 25), 0.97, Draw_objects.random(50, 70), base_hue, 1, 1, 0, Math.PI / 2 * 3);
}

var Conf = /* module */[
  /* is_delete_elem */is_delete_elem,
  /* action_when_delete */action_when_delete,
  /* create_elem */create_elem
];

var include = Draw_objects.Make(Conf);

var elems = include[0];

var update_elem = include[1];

var draw_elem = include[2];

var update = include[3];

var draw = include[4];

var create = include[5];

exports.Conf        = Conf;
exports.elems       = elems;
exports.update_elem = update_elem;
exports.draw_elem   = draw_elem;
exports.update      = update;
exports.draw        = draw;
exports.create      = create;
/* include Not a pure module */
