// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Draw_objects = require("./draw_objects.js");

function is_delete_elem(elem) {
  return +(elem[/* alpha */8] <= elem[/* decay */9]);
}

function action_when_delete() {
  return /* () */0;
}

function create_elem(base_hue, x, y) {
  return Draw_objects.create_elem(3, x, y, Draw_objects.random(1, 20), 0.95, Draw_objects.random(50, 80), Draw_objects.random(base_hue - 50, base_hue + 50), Draw_objects.random(0.8, 1.5), 1, Draw_objects.random(0.005, 0.05), Draw_objects.random(0, Math.PI * 2));
}

var Conf = /* module */[
  /* is_delete_elem */is_delete_elem,
  /* action_when_delete */action_when_delete,
  /* create_elem */create_elem
];

var include = Draw_objects.Make(Conf);

var elems = include[0];

var update_elem = include[1];

var draw_elem = include[2];

var update = include[3];

var draw = include[4];

var create = include[5];

exports.Conf        = Conf;
exports.elems       = elems;
exports.update_elem = update_elem;
exports.draw_elem   = draw_elem;
exports.update      = update;
exports.draw        = draw;
exports.create      = create;
/* include Not a pure module */
