typedef (Int8Array or Int16Array or Int32Array or
         Uint8Array or Uint16Array or Uint32Array or Uint8ClampedArray or
         Float32Array or Float64Array or DataView) ArrayBufferView;

typedef (ArrayBufferView or ArrayBuffer) BufferSource;

typedef unsigned long long DOMTimeStamp;

callback Function = any (any... arguments);

callback VoidFunction = void ();